name: Generate Podcast Feeds
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7.0.1
      - name: Install Dependencies
        run: pip install pyyaml
      - name: Run Feed Generator
        run: python feed.py
      - name: Push to Repository
        run: |
          git config user.name Sean-Paul-Nieves
          git config user.email snnieves@fit.edu.ph
          git add .
          git commit -m "Modified Feed"
          git push
      

  
